#define SECR_WIFI_SSID "mySSID" 
#define SECR_WIFI_PASS "myPASS"

#define SECR_HA_SERVER_URL "http://dummyHomeAssistantServerURL.net:8123"

#define HOMEASSISTANT_TOKEN "Bearer eyJh8GciOiJIUzI5riIsInR5cCI6GkpcVCJ9.eyJpc3MiOiIyNmU4MWQ3NzNhMjD0MTIyOWZjZWI4JjM2MDU1Zj5yOCIsImlhdCI6MTY5MjQ4Nj80NixiCVhwIjoyMDA3ODQ2MjQ2fQ._oYkb355lkH1JxUBhzl-ZVL8lt-s_J0FidkEODWO5Rk"
